### ISSUE TITLE
How to fix StartSession function fail.

### ISSUE THREAD

**Issue by AStasiuk** [smartdevicelink/sdl_atf_test_scripts#11]
Genivi release 4.1.0 has defect with parameters types in RAI response, 
because of this issue from start StartSession function is failed and ATF doesn’t start script execution ( this is ATF feature – in case initial functions are not passed ATF must not execute script ).

So for ATF need to perform some workaround:
1.     Open ‘test_run/modules/connecttest.lua’
2.     Find code
function module:StartSession()
  critical(true)
  self:startSession()
end
3.     And comment or remove string critical(true) in function 
function module:StartSession()
  -- critical(true)
  self:startSession()
end

**Comment by LuxoftAKutsan** [comment]
@AStasiuk why you mentioned it in sdl_atf_test_scripts repository? Why not in https://github.com/smartdevicelink/sdl_atf?

**Comment by jacobkeeler** [comment]
Closing as outdated
