### ISSUE TITLE
Failed ATF script related to audio streaming

### ISSUE THREAD

**Issue by IGapchuk** [smartdevicelink/sdl_atf_test_scripts#2164]
The following Mobile Projection tests currently fail on the develop branch of SDL Core: 

1. ./test_scripts/MobileProjection/Phase2/005_audioStreamingState_111-118.lua
2. ./test_scripts/MobileProjection/Phase2/006_videoStreamingState_001-006.lua

It should be investigated whether these are Core issues (in which case issues should be submitted to the Core repository) or bad test cases.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2163
