### ISSUE TITLE
CloudAdapter: Not caught BC.UpdateAppList message

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2181]
In script:
* [CloudAppRPCs/011_UpdateAppList_NewCloudApplication.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/CloudAppRPCs/011_UpdateAppList_NewCloudApplication.lua)

In `checkUpdateAppList()` local function I would not suggest to use `AnyNumber()` as qualifier for number of expected `BC.UpdateAppList` messages.
In this case message may come or may not come and we won't be sure that defined check will be done.
I suggest to use `Times(1)` instead

However script fails with this modification on latest SDL build (https://github.com/smartdevicelink/sdl_core/commit/1265fce0ec352f4a2a65709960696a77bd4e68fb)

**Comment by dboltovskyi** [comment]
@theresalech please triage this issue

**Comment by jacobkeeler** [comment]
I was hesitant to do `Times(1)` because there could have been other causes for an `UpdateAppList` to be sent, causing more than one message, `Times(AtLeast(1))` might be more appropriate.

In addition, it appears that the test fails due to a merge issue, so I will fix that as well.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2182
