### ISSUE TITLE
Failed ATF scripts for validation of the snapshot because of lock_screen_dismissal_enabled

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2215]
The next scripts should be extended with lock_screen_dismissal_enabled.
External
./test_scripts/Policies/Policy_Table_Update/127_ATF_PTS_Creation_rule.lua
./test_scripts/Policies/Policy_Table_Update/143_ATF_PTU_validation_rules.lua
./test_scripts/Policies/Validation_of_PolicyTables/262_ATF_pt_snapshot_validation_rules_for_omitted_parameters.lua
./test_scripts/Policies/Validation_of_PolicyTables/263_ATF_pt_snapshot_validation_rules_for_required_parameters.lua

Proprietary 
./test_scripts/Policies/build_options/094_ATF_PTS_creation_rule_PROPRIETARY.lua

For now scripts are failed.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2220
