### ISSUE TITLE
Add possibility to run scripts on EXTERNAL_PROPRIETARY and HTTP policy flows

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2229]
Currently default SDL policy flow that is supported by ATF scripts is `PROPRIETARY`
There are 2 other flows `EXTERNAL_PROPRIETARY` and `HTTP` which is supported by SDL.
Currently some scripts can be possible to run on `EXTERNAL_PROPRIETARY` other ones on `HTTP`.
It would be great improvement to make possible to run all scripts on all supported SDL policy flows.

**Comment by iCollin** [comment]
Closed with merge of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2244 and https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2212
