### ISSUE TITLE
Update RC and EUCS test sets

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2230]
Existing tests sets for RC and EUCS require some updates.

1) RC test sets
There are a lot of features were implemented for RC functionality. 
Part of them have the same test scripts. Some sets lack of scripts.
The idea is to have only a few up-to-date test sets to cover whole RC functionality.
E.g.:
  - SDL5_0/rc_CLIMATE_RADIO.txt
  - SDL5_0/rc_AUDIO_LIGHT_HMI_SETTINGS.txt
  - SDL5_0/rc_SEAT.txt
  - SDL5_0/rc_interior_vehicle_data_management.txt
  - SDL5_0/rc_OnRCStatus.txt
And these sets are directly mapped to appropriate folder in scripts

2) EUCS test sets 
These test sets have odd comments.
  - test_sets/ExternalUserConsentStatus_Informing_HMI.txt
  - test_sets/External_Consent_Status_OFF.txt
  - test_sets/External_Consent_Status_ON.txt
  - test_sets/External_UCS-related_params.txt

**Comment by jacobkeeler** [comment]
Closing with the merge of #2211
