### ISSUE TITLE
Improve application activation speed

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2231]
There is an `app.activate()` function in `actions` module.
Currently this function has default delay of 2000 ms.
It was made for the cases with a few apps in order to handle all `OnHMIStatus` notifications for all apps.
Novadays this function is used almost in every script which leads to increase of script execution time.
The idea is to reduce delay for this function.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2232
