### ISSUE TITLE
Improve stability of CloudApp scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2235]
Currently there is one CloudApp script failed occasionally.
  - [CloudAppRPCs/010_get_icon_url](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/CloudAppRPCs/010_get_icon_url.lua)

It's stability needs to be improved.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2236
