### ISSUE TITLE
Improve stability of AppServices scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2237]
Currently there are a few AppServices script failed occasionally.
  - [AppServiceActivation/003_two_apps_activate_success](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/AppServices/AppServiceActivation/003_two_apps_activate_success.lua)
  - [AppServiceActivation/004_two_apps_default_disconnect_reconnect](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/AppServices/AppServiceActivation/004_two_apps_default_disconnect_reconnect.lua)

It's stability needs to be improved.

**Comment by jacobkeeler** [comment]
How often do you see these failures? Also please provide logs for these errors

**Comment by dboltovskyi** [comment]
@jacobkeeler 
Regarding 
```
test_scripts/AppServices/AppServiceActivation/003_two_apps_activate_success.lua
```
It fails not often ~10-20% of runs

Code `ExpectNotification("OnSystemCapabilityUpdated", combinedParams):Times(AtLeast(1))` could fail for 2nd occurrence since validation against `combinedParams` will be done by ATF for all occurrences.
For this particular script payload for 1st occurrence is not the same as for 2nd one.
Please see details in [issue_2237.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/3576695/issue_2237.tar.gz)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2238
