### ISSUE TITLE
Improve stability of SDLPassengerMode scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2239]
Currently there is one SDLPassengerMode script failed occasionally.
  - [SDL_Passenger_Mode/012_OnDD_PT_another_language_exists_ChangeRegistration](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/SDL_Passenger_Mode/012_OnDD_PT_another_language_exists_ChangeRegistration.lua)

It's stability needs to be improved.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2240
