### ISSUE TITLE
Improve stability of SameApp scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2241]
Currently there is one SameApp script failed occasionally.
  - [Subscriptions/010_Two_apps_with_same_appName_DIFF_devices_perform_AudioPassThru](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/TheSameApp/Subscriptions/010_Two_apps_with_same_appName_DIFF_devices_perform_AudioPassThru.lua)

These issues needs to be resolved

**Comment by jacobkeeler** [comment]
@dboltovskyi #2242 does not fix the listed `Security` scripts, correct? Will there be a separate PR for those?

**Comment by dboltovskyi** [comment]
@jacobkeeler You're right. Fix for security was moved to https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2252.
The main idea was to create a single issue to align scripts for a new proposals between each other.
Description of current issue is updated to mention the only one script with timeout that was found when the feature was merged develop.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2242
