### ISSUE TITLE
Rework VehicleData scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2243]
Rework implementation of VehicleData scripts in order to use advantages of new common modules.
This simplify logic and allow to run scripts on all SDL policy flows (https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2229)

**Comment by iCollin** [comment]
Closed with merge of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2244
