### ISSUE TITLE
Improve stability of Handling VR Help scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2248]
Currently there is one Handling VR Help script failed occasionally.
  - [Handling_VR_help_requests/003_SetGlobalProp_without_deleted_commands](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/SDL5_0/Handling_VR_help_requests/003_SetGlobalProp_without_deleted_commands.lua)

It's stability needs to be improved.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2252
