### ISSUE TITLE
Improve stability of Policy scripts - additional updates

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2259]
Continuous run of regression test pack revealed a few more policy scripts which are failed occasionally.
 - [App_Permissions/002_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/App_Permissions/002_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration.lua)
 - [Validation_of_PolicyTables/227_ATF_usage_and_error_counts_update_count_sync_out_of_memory](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/227_ATF_usage_and_error_counts_update_count_sync_out_of_memory.lua)
 - [Validation_of_PolicyTables/228_ATF_usage_and_error_counts_update_count_of_sync_reboots](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/228_ATF_usage_and_error_counts_update_count_of_sync_reboots.lua)
 - [Validation_of_PolicyTables/229_ATF_usage_and_error_counts_update_count_of_iap_buffer_full](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/229_ATF_usage_and_error_counts_update_count_of_iap_buffer_full.lua)
 - [Validation_of_PolicyTables/230_ATF_usage_and_error_counts_update_minutes_in_hmi_none](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/230_ATF_usage_and_error_counts_update_minutes_in_hmi_none.lua)
 - [Validation_of_PolicyTables/231_ATF_usage_and_error_counts_update_minutes_in_hmi_limited](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/231_ATF_usage_and_error_counts_update_minutes_in_hmi_limited.lua)
 - [Validation_of_PolicyTables/232_ATF_usage_and_error_counts_update_minutes_in_hmi_full](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/232_ATF_usage_and_error_counts_update_minutes_in_hmi_full.lua)
 - [Validation_of_PolicyTables/233_ATF_usage_and_error_counts_update_minutes_in_hmi_background](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/Validation_of_PolicyTables/233_ATF_usage_and_error_counts_update_minutes_in_hmi_background.lua)
 - [user_consent_of_Policies/221_ATF_Factory_reset](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/user_consent_of_Policies/221_ATF_Factory_reset.lua)

These scripts needs to be stabilized
This issue is a continuation of https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2233

**Comment by theresalech** [comment]
Closed via #2260
