### ISSUE TITLE
Failed scripts for iAP2TransportSwitch feature

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2262]
On a current SDL [develop](https://github.com/smartdevicelink/sdl_core/commit/3ea6b1a35c2ff77220e2915ff9efdf6226115314) build all ATF test scripts for `iAP2TransportSwitch` feature are failed.

After investigation it was found out the root causes:

 - `001` became failed due to merge of [#2924](https://github.com/smartdevicelink/sdl_core/pull/2924)
 - `002` - `004` - became failed due to merge of [#2960](https://github.com/smartdevicelink/sdl_core/pull/2960)

It seems fails related to SDL core and need to be fixed in appropriate repository.

**Comment by theresalech** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3034
