### ISSUE TITLE
Improve stability of SameApp scripts - additional update

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2266]
Currently there is two `TheSameApp` script failed occasionally:
  - [Resumption/001_Resumption_IGNITION_OFF_same_app_on_different_devices](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/TheSameApp/Resumption/001_Resumption_IGNITION_OFF_same_app_on_different_devices.lua)
  - [Resumption/002_Resumption_unexpected_disconnect_same_app_on_different_devices](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/TheSameApp/Resumption/002_Resumption_unexpected_disconnect_same_app_on_different_devices.lua)

These issues needs to be resolved

**Comment by iCollin** [comment]
Closed via #2267
