### ISSUE TITLE
Failed API/049 script from smoke

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2270]
Script [Smoke/API/049_SetMenuLayout_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/049_SetMenuLayout_SUCCESS.lua) sometimes failed with message:
```
[13:39:21,919] Setting_Menu_Layout_to_supported_TILES                                                [FAIL] (10761 ms)
 HMI call UI.SetGlobalProperties: Timeout: HMI call UI.SetGlobalProperties: Timeout expired
```

The reason of that all 3 messages `BC.OnSystemCapabilityUpdated`, `SetGlobalProperties` and `AddSubMenu` are send almost simultaneously.

This needs to be corrected

**Comment by iCollin** [comment]
Closed via #2271
