### ISSUE TITLE
Include new scripts to API/Smoke test set

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2273]
Currently there are a few scripts which are in `test_scripts/Smoke/API` folder however missed in `smoke_tests.txt` test set
 - [051_GetInteriorVehicleDataConsent_PositiveCase_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/051_GetInteriorVehicleDataConsent_PositiveCase_SUCCESS.lua)
 - [051_GetPolicyConfigurationData_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/051_GetPolicyConfigurationData_SUCCESS.lua)
 - [052_ReleaseInteriorVehicleDataModule_PositiveCase_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/052_ReleaseInteriorVehicleDataModule_PositiveCase_SUCCESS.lua)
 - [053_GetInteriorVehicleData_PositiveCase_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/053_GetInteriorVehicleData_PositiveCase_SUCCESS.lua)

The idea is to include these scripts into smoke test set

**Comment by jacobkeeler** [comment]
Closing with the merge of #2274
