### ISSUE TITLE
Improve stability of scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2276]
Currently following ATF scripts occasionally failed to different reasons:
  - [MobileProjection/Phase2/005_audioStreamingState_111-118](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase2/005_audioStreamingState_111-118.lua)
  - [MobileProjection/Phase2/smoke/005_audioStreamingState_111-118](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase2/smoke/005_audioStreamingState_111-118.lua)
  - [Policies/build_options/072_ATF_PTU_PM_Sets_Status_UPDATE_NEEDED_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/072_ATF_PTU_PM_Sets_Status_UPDATE_NEEDED_HTTP.lua)
  - [Policies/App_Permissions/022_ATF_No_Permission_Notification_To_HMI_In_First_App_Registration](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/App_Permissions/022_ATF_No_Permission_Notification_To_HMI_In_First_App_Registration.lua)

Their stability needs to be improved

**Comment by jacobkeeler** [comment]
Closing with the merge of #2277
