### ISSUE TITLE
Improve stability of scripts - a few more updates required

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2278]
Currently following ATF scripts occasionally failed to different reasons:
  - [052_ATF_PTU_Trigger_IGN_Cycles_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/052_ATF_PTU_Trigger_IGN_Cycles_HTTP.lua)
  - [188_ATF_HP_Device_Data_Section_Validation](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/user_consent_of_Policies/188_ATF_HP_Device_Data_Section_Validation.lua)
  - [020_SetGlobalProp_absence_after_custom_request_after_resumption](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/SDL5_0/Handling_VR_help_requests/020_SetGlobalProp_absence_after_custom_request_after_resumption.lua)
(and also `021` - `024`)
  - [007_1_ChangeReg_two_apps_with_diff_appName_diff_appID_from_DIFF_devices](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/TheSameApp/Registration/007_1_ChangeReg_two_apps_with_diff_appName_diff_appID_from_DIFF_devices.lua)
(and also `007_2`, `007_3`, `008`)
  - [011_ListFiles_PositiveCase_SUCCESS](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Smoke/API/011_ListFiles_PositiveCase_SUCCESS.lua)
  - [022_Video_service_protected_PTU_FAILED_TimeOut_failed_success_2rd_try_failed_external](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/ServiceStatusUpdateToHMI/022_Video_service_protected_PTU_FAILED_TimeOut_failed_success_2rd_try_failed_external.lua)

Their stability needs to be improved

**Comment by iCollin** [comment]
Closed via #2279
