### ISSUE TITLE
Failed script for issue 1772

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2314]
Script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1772_update_default_section.lua is failed because od wrong sent response for GetVehicleData.

SDL core: https://github.com/smartdevicelink/sdl_core/commit/e137556512215ded94228e33d21ab4c3e1af3017
ATF scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/6f43bfd3eba059a82db5f3ee2a3e00d3e1f5efbb
ATF: develop

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2310
