### ISSUE TITLE
Failed scripts because of a redundant OnPerfmissionChange notification

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2330]
SDL: https://github.com/smartdevicelink/sdl_core/commit/fcdacd760c6182e73f3517b3baa0dd10660ff0e8
Scripts: 1f664c4
ATF: develop

Failed scripts because of a redundant OnPerfmissionChange notification on the external policy flow.

Scripts:
./test_scripts/Defects/4_5/1873_Parameters_empty_in_policy_table.lua
./test_scripts/Defects/5_0/1032_CreateInteractionChoiceSet_core_successfully_creates_choice_set_with_duplicate_vrCommands_menuName_inside_it.lua

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2339
