### ISSUE TITLE
Scripts actualization from Trigger_PTU_NO_Certificate

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2331]
SDL: smartdevicelink/sdl_core@fcdacd7
Scripts: 1f664c4
ATF: develop

Scripts actualization from Trigger_PTU_NO_Certificate

https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2337
