### ISSUE TITLE
Specify the policy flow in scripts for defects

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2332]
SDL: smartdevicelink/sdl_core@fcdacd7
Scripts: 1f664c4
ATF: develop

Specify the policy flow in scripts in case script is written for some exact flow.

https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/Defects

**Comment by jacobkeeler** [comment]
Closing with the merge of #2336
