### ISSUE TITLE
Failed script for 1921 issue

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2333]
SDL: smartdevicelink/sdl_core@fcdacd7
Scripts: 1f664c4
ATF: develop

Failed script for issue 1772

https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua

**Comment by jacobkeeler** [comment]
Closing with the merge of #2335
