### ISSUE TITLE
Align scripts designed for 3142 with fix for 3123

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2345]
Behavior described in https://github.com/smartdevicelink/sdl_core/issues/3142 and initially implemented was slightly modified by https://github.com/smartdevicelink/sdl_core/issues/3123 which were merged later. That's why scripts created for 3142 needs to be adjusted.

**Comment by iCollin** [comment]
Closed via #2346
