### ISSUE TITLE
Wrong expected reason in OnAppInterfaceUnregistered during FACTORY_DEFAULTS exit

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2355]
Script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/user_consent_of_Policies/221_ATF_Factory_reset.lua has wrong expectation of OnAppInterfaceUnregistered in line 52.

Actual result:
EXPECT_NOTIFICATION("OnAppInterfaceUnregistered", { reason = "IGNITION_OFF" })

Expected result:
EXPECT_NOTIFICATION("OnAppInterfaceUnregistered", { reason = "FACTORY_DEFAULTS" })

ATF: develop
Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/ba6952752254797a2f31a7e8136310d616202d3d

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2354
