### ISSUE TITLE
Add policy mode restrictions to policy scripts

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2362]
Current implementation of [Policies](https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/Policies) scripts does not have restrictions on SDL policy mode which particular script is applicable to.
Task is to add such restrictions in way that script will be skipped if it's no applicable for selected SDL policy mode.

**Comment by iCollin** [comment]
Closed via #2363
