### ISSUE TITLE
Failed 2457 script because of the expectation in UpdateDeviceList

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2365]
Failed [2457](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2457_Needed_fixes_sending_of_UpdateDeviceList_notification_on_device_connect.lua) script because of the expectation in UpdateDeviceList.

ATF: develop
Script: develop 94f92bb

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2422
