### ISSUE TITLE
Random fail in 1893 script

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2374]
Random fail in [1893](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/4_5/1893_ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua) script
It fails in 30% of runs.

ATF:develop
SDL: develop

**Comment by dboltovskyi** [comment]
Issue is not reproduced at https://github.com/smartdevicelink/sdl_core/commit/908b473c971e98581dbc7fd026361406766b81c0 and https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/2f85e5ed1b68ea70b422ccb74d6adaf8de548287 using any of available policy modes and connection types

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2424
