### ISSUE TITLE
Failed 2446, 2670_4 scripts after the merge of 3279 fix

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2376]
Failed [2446](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2446_SDL_doesn_t_resume_HMILevel_when_DEACTIVATE_HMI_with_isActive_is_true_then_false.lua), [2670_4](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua) scripts after the merge of #[3279](https://github.com/SmartDeviceLink/sdl_core/issues/3279) fix

Scripts: develop
ATF: develop
SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.1.0

**Comment by jacobkeeler** [comment]
Closing with the merge of #2375
