### ISSUE TITLE
Wrong expectation on SubscribeVehicleData HMI call in two test scripts from develop

### ISSUE THREAD

**Issue by ychernysheva** [smartdevicelink/sdl_atf_test_scripts#2385]
Test scripts test_scripts/API/VehicleData/GenericNetworkSignalData/032_Subscription_resumption_for_VDitems_2_apps_unexpected_disconnect.lua and test_scripts/API/VehicleData/GenericNetworkSignalData/033_Subscription_resumption_for_VDitems_2_apps_ign_off.lua failed after fixing issue https://github.com/SmartDeviceLink/sdl_core/issues/2283.

Scripts: develop (49fc2be922f89d24340f0040653147e9b87bce5c)
ATF: develop (496be121cf530c6b87d5e54d9b8acb5139fd5d5b)
SDL: branch with fix (https://github.com/ychernysheva/sdl_core/tree/fix/sdl_sends_subscribe_vehicle_data_to_same_items_during_resumption)

**Comment by jacobkeeler** [comment]
Closing with the merge of #2386
