### ISSUE TITLE
025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua is missed in all test sets

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2395]
Script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua is missed in all test sets.

Scripts: a7db5cc

**Comment by dboltovskyi** [comment]
Issue is not actual since script is included into:
https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/39695756822fb5779a33740f77f512a2cd84c4b9/test_sets/SDL5_0/mobile_projection_2.txt#L24
