### ISSUE TITLE
Wrong OnHMIStatus expectation in 025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2404]
The wrong expectation in https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/a2040dbff1bc43b4008a71b6e6c1c58fc0dd93fa/test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua#L58

The first app should expect the changing of `audioStreamingState` back to `AUDIBLE` state, and the second app should expect 0 OnHMIlevel notification.

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2405
