### ISSUE TITLE
Fails in Persisting HMI Capabilities scripts 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_atf_test_scripts#2455]
The following scripts are failed if SDL was built with `BUILD_WEBSOCKET_SERVER_SUPPORT=OFF`

-  ./test_scripts/Capabilities/PersistingHMICapabilities/032_Suspending_of_RAI_request_processing_during_OnReady_with_another_ccpu_version_in_case_cache_file_exists.lua
-  ./test_scripts/Capabilities/PersistingHMICapabilities/033_Suspending_of_RAI_request_processing_during_OnReady_in_case_no_cap_response.lua
- ./test_scripts/Capabilities/PersistingHMICapabilities/034_Suspending_of_RAI_request_processing_during_OnReady_in_case_cache_file_does_not_exist_no_cap_response.lua

SDL: develop (10f19d1b)
ATF: develop (42a2e37)
Scripts: develop (20887a48)

Test results: [1746.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5268583/1746.zip)

**Comment by LitvinenkoIra** [comment]
This is a regression issue, reproduced only for 7.0

**Comment by jacobkeeler** [comment]
Closing with the merge of #2456
