### ISSUE TITLE
Fails in WebEngineProjection scripts for WSS transport

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf_test_scripts#2458]
In case if default transport is `WSS` the following scripts are failed:
- ./test_scripts/WebEngine/WebEngineProjection/014_HMI_status_transitions_different_applications_interactions.lua
- ./test_scripts/WebEngine/WebEngineProjection/027_OnExitApplication_RESOURCE_CONSTRAINT_multiple_apps_on_different_connections.lua

SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (a36ea82)
ATF: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop (6e7d086)
Scripts: https://github.com/smartdevicelink/sdl_atf/tree/develop (42a2e37)

ATF Reports:
[014_Console.txt.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5269350/014_Console.txt.tar.gz)
[027_Console.txt.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5269351/027_Console.txt.tar.gz)

**Comment by dboltovskyi** [comment]
This is a regression issue, reproduced only for 7.0

**Comment by jacobkeeler** [comment]
Closing with the merge of #2459
