### ISSUE TITLE
001_OnSystemRequest_send_binaryData_for_any_requestType.lua is missed in all test sets

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2492]
Script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/System/OnSystemRequest/001_OnSystemRequest_send_binaryData_for_any_requestType.lua is missed in all test sets.

Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/cce29e5f0a762db2bbcc106f57337cdd00e77d45

**Comment by dboltovskyi** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2503
