### ISSUE TITLE
Redundant OnHMIStatus(NONE) notification during Activate App in script '842_App_does_not_activate_when_policies_are_disabled'

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2624]
**Redundant  OnHMIStatus(NONE) notification during Activate App in script**
./test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua

Sometimes script is failed with error:
[09:53:26,845] Register_App [SUCCESS] (121 ms)
— Test --------------------------------------------------------------------------------------------
[09:53:26,968] Activate_App [FAIL] (27 ms)
OnHMIStatus notification: ValidIf:
payload.hmiLevel: expected: FULL, actual value: NONE

**Observed Behavior:**
Redundant  OnHMIStatus(NONE) notification during Activate App

**Expected Behavior**
The app should expect OnHMIlevel(NONE) notification during Register App

**Occurrence:** ~1%

**Logs:**
[Logs_SDL_842.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/7895788/Logs_SDL_842.zip)

**OS & Version Information:**

  SDL: develop (8f1ccb29)
  SCR: develop (454b47ba)

**Comment by VjKlepikov** [comment]
@theresalech Please notice Luxoft team is going to prepare a fix for ATF script(s)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2625
