### ISSUE TITLE
Timeout expired for 'Lock Screen URL event' in script '3674_2_HMI_starts_PTU_before_UpdateAppList.lua'

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2627]
Timeout expired for 'Lock Screen URL event' in script 'test_scripts/Defects/8_0/3674_2_HMI_starts_PTU_before_UpdateAppList.lua'
./test_scripts/Defects/8_0/3674_2_HMI_starts_PTU_before_UpdateAppList.lua 

Sometimes the script is failed with error:
— Test --------------------------------------------------------------------------------------------
PTS file was not found, PreloadedPT is used instead
App 1 was used for PTU
[10:46:14,333] Register_App_With_Immediate_PTU [FAIL] (12477 ms)
Lock Screen URL event: Timeout: Lock Screen URL event: Timeout expired
[10:46:26,811] Activate_App [SUCCESS] (392 ms)

**Occurrence:** ~1%

**Observed Behavior:**
Timeout expired for 'Lock Screen URL event
( Call the expectation function for 'Lock Screen URL' event after BasicCommunication.OnAppRegistered notification )

**Expected Behavior**
Call the expectation function for 'Lock Screen URL' event after RegisterAppInterface response

Logs:
[2022-01-18_10-23-29.977_failed.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/7971395/2022-01-18_10-23-29.977_failed.tar.gz)

**OS & Version Information:**
Ubuntu 20
SDL: develop (8f1ccb29)
SCR: develop (454b47ba) 
ATF: develop

**Comment by VjKlepikov** [comment]
@theresalech Please notice Luxoft team is going to prepare a fix for ATF script(s)

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2628
