### ISSUE TITLE
Mobile app send SystemRequest from different app than the one which Core requested the PTU from

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2634]
Mobile app send SystemRequest from different app than the one which Core requested the PTU from in script:
./test_scripts/Policies/build_options/078_ATF_PTU_HMI_Level_Affected_Apps_FULL_LIMITED_HTTP.lua

Note: Issue is applicable for tests:
./test_scripts/Protocol/NACKReason/004_Invalid_Certificate_NACK.lua

#### Steps:

1.  Core and HMI are started
2.  App1 and App2 are registered
3. Core sends OnStatusUpdate UPDATING
4. SDL send OnSystemRequest to APP1

#### Observed Behavior:
Mobile App2 sent SystemRequest(HTTP) to SDL

#### Expected Behavior
Mobile App1 sent SystemRequest(HTTP) to SDL

#### Logs:
[Logs.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/8078432/Logs.zip)

OS & Version Information:
Ubuntu 18
SDL: develop (b74c738)
SCR: develop https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop ([c7e8aa2](https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/c7e8aa2f94bd48f11a260cc501952e344ac2c90a))
ATF: develop

**Comment by VjKlepikov** [comment]
Please notice this is a regression issue that became reproducible after merge of https://github.com/smartdevicelink/sdl_core/pull/3853

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2637

**Comment by VjKlepikov** [comment]
@iCollin Please note https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2646
