### ISSUE TITLE
Test fail during Activate app in script 1903_Media_app_is_not_activated_during_active_embedded_navigation.lua

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2643]
Test fail during Activate app in script 1903_Media_app_is_not_activated_during_active_embedded_navigation.lua
./test_scripts/Defects/7_0/1903_Media_app_is_not_activated_during_active_embedded_navigation.lua

Sometimes the script is failed with errors:
— Test --------------------------------------------------------------------------------------------
[06:56:48,956] Media_app_during_active_embedded_audio_source [SUCCESS] (398 ms)
[06:56:49,354] Activate_media_app [FAIL] (32 ms)
OnHMIStatus notification: ValidIf:
payload.hmiLevel: expected: FULL, actual value: LIMITED
OnHMIStatus notification: Times: The most allowed occurences boundary exceed

Occurrence: ~1%

Logs:
[2022-02-16_06-35-27.232_failed.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/8140489/2022-02-16_06-35-27.232_failed.tar.gz)

OS & Version Information:
Ubuntu_18.04
  SDL: develop (b74c7381)
  SCR: develop (0551543)

**Comment by JackLivio** [comment]
Resolved with merge!
