### ISSUE TITLE
Sometimes HMI sends invalid value for heading parameter during GetVehicleData request in script 001_GetVD_Success_flow.lua

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2655]
[ATF script] HMI sends invalid value for heading parameter during GetVehicleData request in script ./test_scripts/API/VehicleData/GetVehicleData/001_GetVD_Success_flow.lua

**Occurrence:** ~0.1%

Sometimes the script is failed with errors:
— VD parameter: gps -------------------------------------------------------------------------------
— Test type: VALID_RANDOM_ALL ---------------------------------------------------------------------
[12:52:42,484] Param_gps [SUCCESS] (400 ms)
— Test type: VALID_RANDOM_SUB ---------------------------------------------------------------------
[12:52:42,885] Param_gps_actual [SUCCESS] (400 ms)
[12:52:43,285] Param_gps_altitude [SUCCESS] (399 ms)
[12:52:43,684] Param_gps_compassDirection [SUCCESS] (400 ms)
[12:52:44,084] Param_gps_dimension [SUCCESS] (401 ms)
[12:52:44,486] Param_gps_hdop [SUCCESS] (398 ms)
[12:52:44,885] Param_gps_heading [FAIL] (399 ms)
Response to 127: ValidIf:
type of data payload.gps: expected table, actual type: nil

ATF log:
===== Param_gps_heading :
MOB->SDL [02-04-2022 12:52:44,885] [rpcFunction: GetVehicleData, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 128, binaryDataSize: 0] :
{"gps":true}

SDL->HMI [02-04-2022 12:52:44,889] {"id":152,"jsonrpc":"2.0","method":"VehicleInfo.GetVehicleData","params":{"gps":true}}

HMI->SDL [02-04-2022 12:52:44,889] {"id":152,"jsonrpc":"2.0","result":{"code":0,"gps":{**"heading":360**,"latitudeDegrees":-57.31,"longitudeDegrees":-178.2},"method":"VehicleInfo.GetVehicleData"}}

SDL->MOB [02-04-2022 12:52:44,897] [rpcFunction: GetVehicleData, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 132, binaryDataSize: 0] :
{"success":false,"resultCode":"GENERIC_ERROR","info":"Invalid message received from vehicle"}

**Steps:**
1) SDL and HMI are started
2) GetVehicleData RPC and 'gps' parameter are allowed by policies
3) App is registered
4) App sends valid GetVehicleData('gps'=true) request to SDL
SDL transfers this request to HMI
5) HMI sends VI.GetVehicleData response with <vd_param> data to SDL

**Expected Behavior:**
HMI sends VI.GetVehicleData response with valid 'heading' parameter to SDL

**Observed Behavior**
HMI sends invalid value for heading parameter "heading":360

**Occurrence:** ~0.1%

Logs: 
[2022-04-02_12-45-01.065_failed.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/8426608/2022-04-02_12-45-01.065_failed.tar.gz)

**OS & Version Information:**
OS/Version: Ubuntu 18.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/8.1.0 (b30f012)
ATF: latest
Scripts: https://github.com/smartdevicelink/sdl_core/tree/develop (b74c738)

**Comment by jacobkeeler** [comment]
Closed via #2656
