### ISSUE TITLE
Test fail during Subscribe Soft button in script 009_SubscribeButton_CUSTOM_BUTTON_resumption_IGN_OFF_ON_not_supported_by_HMI.lua

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2657]
Test fail during Subscribe Soft button in script ./test_scripts/API/ButtonSubscription/Capabilities/009_SubscribeButton_CUSTOM_BUTTON_resumption_IGN_OFF_ON_not_supported_by_HMI.lua

Sometimes the script is failed with errors:
— Test --------------------------------------------------------------------------------------------
[00:22:48,916] Reregister_App_resumption_data [SUCCESS] (3061 ms)
[00:22:51,977] Subscribe_on_Soft_button [FAIL] (12000 ms)
HMI call UI.Show: Timeout: HMI call UI.Show: Timeout expired
Response to 3: ValidIf:
payload.success: expected: true, actual value: false

**ATF log:**
===== Subscribe_on_Soft_button :

MOB->SDL [03-04-2022 00:22:51,977] [rpcFunction: Show, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 4, binaryDataSize: 0] : {"softButtons":[{"isHighlighted":false,"type":"TEXT","text":"Button1","softButtonID":1,"systemAction":"DEFAULT_ACTION"}]} 

SDL->MOB [03-04-2022 00:22:51,986] [rpcFunction: Show, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 6, binaryDataSize: 0] : {"resultCode":"DISALLOWED","success":false} 

SDL->MOB [03-04-2022 00:22:52,009] [rpcFunction: OnHMIStatus, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 7, binaryDataSize: 0] : {"videoStreamingState":"STREAMABLE","systemContext":"MAIN","hmiLevel":"FULL","audioStreamingState":"AUDIBLE","windowID":0} 

**Occurrence:**  ~1%

 **Logs:**
[2022-04-03_00-22-29.622_failed.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/8427886/2022-04-03_00-22-29.622_failed.tar.gz)

**OS & Version Information:**
Ubuntu_20.04
SDL: release/8.1.0 (cbc9d392)
SCR: develop (caf997ae)

**Comment by jacobkeeler** [comment]
closed via #2658
