### ISSUE TITLE
Sometimes test fail with attempt to call field 'cprint' (a nil value) in script 008_SubscribeButton_Resumption_IGN_OFF_ON.lua

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_atf_test_scripts#2685]
Sometimes test fail with attempt to call field 'cprint' (a nil value) in script ./test_scripts/API/ButtonSubscription/SubscribeButton_UnsubscribeButton/008_SubscribeButton_Resumption_IGN_OFF_ON.lua'

Sometimes the script is failed with error:
— Preconditions -----------------------------------------------------------------------------------
kill: (137): No such process
[01:52:27,974] Clean_environment [SUCCESS] (402 ms)
SDL pid 163
tcp 0 0 127.0.0.1:8087 0.0.0.0:* LISTEN
SDL started
HMI initialized
HMI is ready
Mobile 1 connected
SDL allowed
[01:52:29,410] Start_SDL_HMIconnect_Mobile_start_Session [SUCCESS] (1034 ms)
[01:52:30,466] App_registration [SUCCESS] (290 ms)
[01:52:30,757] App_activation [SUCCESS] (257 ms)
[01:52:31,014] SubscribeButton_PRESET_0 [SUCCESS] (399 ms)
[01:52:31,412] On_Button_Press_PRESET_0 [SUCCESS] (401 ms)
Mobile 1 disconnected
Lua panic: ...ipts/API/ButtonSubscription/commonButtonSubscription.lua:379: attempt to call field 'cprint' (a nil value) (/home/jenkins/workspace/Issue_12637_ATF_BUILD_RUNNER/src/remote_adapter/remote_adapter_client/lua_remote_library.cc:16)

**Occurrence:** 0.1%

**OS & Version Information:**
OS/Version: Ubuntu 18.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (65947fd)
Script: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop (691c305)

**Logs:** 
[Logs_script_issue.tar.gz](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/8877898/Logs_script_issue.tar.gz)

**Comment by VjKlepikov** [comment]
Luxoft is going to fix this issue

**Comment by theresalech** [comment]
Closed via #2688
