### ISSUE TITLE
Wrong and outdated usage of unpack function in scripts

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2692]
In Scripts there is wrong and outdated usage of unpack function:
1. Unpack function should be used only for arrays, in case of indexed tables unpack function returns nil
2. In Lua version > 5.1 unpack is moved into the table library so usage: table.unpack

SCR: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop ([caf997a](https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/caf997ae9b85a3d3b319236e90a3e7f5cb581137))

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2690
